export const genders = ["male", "female", "other", "unknown"]
export const matrimonialeSituation = [{code : "M", display: "Married"}, {code : "D", display: "Divorced"},  {code : "A", display: "Annuled"},  {code : "U", display: "unmarried"},  {code : "S", display: "Never Married"}]
export const adressUse = ["home", "work"]
export const adressType = ["postal" , "physical", "both"]
export const telecomUse = ["home", "work", "temp", "old", "mobile"]
export const telecomSystem = ["phone", "fax", "email", "pager", "url", "sms", "other"]
export const nameUse = ["usual", "official", "temp", "nickname", "anonymous" ,"old",  "maiden"]
export const namePrefix = ["Mr", "Mrs", "Miss", "Ms"]